### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Xanbert** [Xanbert/vnx#3]
## depent part

- [ ] rwlock
- [ ] high performance map (maybe rbtree)
- [ ] qstr
- [ ] transplant an alloc algorithm

## kernel part

- [ ] task scheduler
- [ ] lazy alloc
- [ ] full support of fat
- [ ] more file and proc syscalls
- [ ] split kernel thread for async syscall

## userspace

- [ ] testsuites and more testsuites
